# Generated by Django 3.2.2 on 2022-05-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='number',
            field=models.CharField(help_text='Sequence ，less than 5 pics', max_length=50, verbose_name='Number'),
        ),
    ]
