# Generated by Django 3.2.2 on 2022-05-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_carousel_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='img_url',
            field=models.ImageField(upload_to='images/carousel/'),
        ),
    ]
