# Generated by Django 3.2.2 on 2022-06-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_carousel_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainclouth',
            name='orig_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='orig_price'),
        ),
        migrations.AlterField(
            model_name='mainclouth',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='price'),
        ),
    ]
