# Generated by Django 3.2.2 on 2022-06-23 05:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0009_auto_20220620_0630'),
        ('order', '0011_ordermaster_total_price_and_more'),
        ('accounts', '0005_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='create_p',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='get_p',
            new_name='rep_in',
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='评论内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ordermaster', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='notification',
            name='quotation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customize.quotation', verbose_name='Quotation'),
        ),
        migrations.AddField(
            model_name='notification',
            name='rep_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rep_comments', to='accounts.notification', verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
