# Generated by Django 3.2.2 on 2022-06-22 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_articlecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notification_related', to='accounts.ouser', verbose_name='评论人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='the_comment', to='accounts.articlecomment', verbose_name='所属评论'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default=1, verbose_name='评论内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_child_comments', to='accounts.notification', verbose_name='父评论'),
        ),
        migrations.AddField(
            model_name='notification',
            name='rep_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rep_comments', to='accounts.notification', verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
