# Generated by Django 3.2.2 on 2022-06-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220623_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='customer_id',
            new_name='from_user_id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='rep_in',
            new_name='to_user_id',
        ),
    ]
