# Generated by Django 3.2.2 on 2022-05-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0002_auto_20220514_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='description',
            field=models.CharField(blank=True, default='需求描述', max_length=230, null=True, verbose_name='需求描述'),
        ),
    ]
