# Generated by Django 3.2.2 on 2022-05-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0003_alter_quotation_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoinprog',
            old_name='reg_id',
            new_name='rep_id',
        ),
    ]
