# Generated by Django 3.2.2 on 2022-05-16 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0004_rename_reg_id_quoinprog_rep_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='is_assinged',
            new_name='is_assigned',
        ),
    ]
