# Generated by Django 3.2.2 on 2022-05-16 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0006_alter_quoinprog_quotation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoinprog',
            name='quotation_id',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='customize.quotation'),
        ),
    ]
