# Generated by Django 3.2.2 on 2022-06-18 20:44

import customize.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0007_alter_quoinprog_quotation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='req_image',
            field=models.ImageField(blank=True, null=True, upload_to=customize.models.quotation_directory_path, verbose_name='定制样式图片'),
        ),
    ]
