# Generated by Django 3.2.2 on 2022-06-20 06:30

import customize.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customize', '0008_alter_quotation_req_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_id',
            field=models.IntegerField(verbose_name='id'),
        ),
        migrations.CreateModel(
            name='tempQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.IntegerField(verbose_name='id')),
                ('sleeve', models.CharField(default='袖子', max_length=50)),
                ('color', models.CharField(default='颜色', max_length=50)),
                ('size', models.CharField(default='尺寸', max_length=50)),
                ('gender', models.CharField(default='性别', max_length=50)),
                ('part_number', models.CharField(default='物料编码', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('req_image', models.ImageField(blank=True, null=True, upload_to=customize.models.quotation_directory_path, verbose_name='定制样式图片')),
                ('description', models.CharField(blank=True, default='需求描述', max_length=230, null=True, verbose_name='需求描述')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_open', models.BooleanField(default=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('category_name', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='customize.category')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='客户')),
            ],
            options={
                'verbose_name': 'tempquotation',
                'verbose_name_plural': 'tempquotation',
                'ordering': ['quotation_id'],
            },
        ),
    ]
