# Generated by Django 3.2.2 on 2022-05-22 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customize', '0007_alter_quoinprog_quotation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordermaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='询价号')),
                ('ship_to_address', models.CharField(default='发货地址', max_length=300)),
                ('ship_to_city', models.CharField(default='发货城市', max_length=100)),
                ('ship_to_state', models.CharField(default='发货州', max_length=50)),
                ('ship_to_zipcode', models.CharField(default='发货zipcode', max_length=300)),
                ('receiver_name', models.CharField(default='收货人', max_length=100)),
                ('receiver_tel', models.CharField(default='收货人电话', max_length=100)),
                ('price', models.CharField(default='货款', max_length=100)),
                ('quotation_id', models.IntegerField(verbose_name='询价号')),
                ('sleeve', models.CharField(default='袖子', max_length=50)),
                ('color', models.CharField(default='颜色', max_length=50)),
                ('size', models.CharField(default='尺寸', max_length=50)),
                ('gender', models.CharField(default='性别', max_length=50)),
                ('part_number', models.CharField(default='物料编码', max_length=50)),
                ('quantity', models.IntegerField(default=0, max_length=50)),
                ('req_image', models.ImageField(upload_to='', verbose_name='定制样式图片')),
                ('description', models.CharField(blank=True, default='需求描述', max_length=230, null=True, verbose_name='需求描述')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_open', models.BooleanField(default=True)),
                ('rep_id', models.BooleanField(default=False, verbose_name='accounts.Ouser')),
                ('category_name', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='customize.category')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='客户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Cartmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField(verbose_name='购物车号码')),
                ('price', models.CharField(default='货款', max_length=100)),
                ('quotation_id', models.IntegerField(verbose_name='询价号')),
                ('sleeve', models.CharField(default='袖子', max_length=50)),
                ('color', models.CharField(default='颜色', max_length=50)),
                ('size', models.CharField(default='尺寸', max_length=50)),
                ('gender', models.CharField(default='性别', max_length=50)),
                ('part_number', models.CharField(default='物料编码', max_length=50)),
                ('quantity', models.IntegerField(default=0, max_length=50)),
                ('req_image', models.ImageField(upload_to='', verbose_name='定制样式图片')),
                ('description', models.CharField(blank=True, default='需求描述', max_length=230, null=True, verbose_name='需求描述')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_open', models.BooleanField(default=True)),
                ('rep_id', models.CharField(default='业务员', max_length=50)),
                ('category_name', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='customize.category')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='客户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'ordering': ['cart_id'],
            },
        ),
    ]
