# Generated by Django 3.2.2 on 2022-06-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_cartmaster_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmaster',
            name='quantity',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='cartmaster',
            name='quotation_id',
            field=models.CharField(default='quotation号码', max_length=100),
        ),
    ]
