# Generated by Django 3.2.2 on 2022-06-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220612_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmaster',
            name='price',
            field=models.FloatField(max_length=100),
        ),
    ]
