# Generated by Django 3.2.2 on 2022-06-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_cartmaster_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='customer_id',
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='color',
            field=models.CharField(default='颜色', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='gender',
            field=models.CharField(default='性别', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='part_number',
            field=models.CharField(default='物料编码', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='quantity',
            field=models.IntegerField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='receiver_name',
            field=models.CharField(default='收货人', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='receiver_tel',
            field=models.CharField(default='收货人电话', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='req_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='定制样式图片'),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='ship_to_address',
            field=models.CharField(default='发货地址', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='ship_to_city',
            field=models.CharField(default='发货城市', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='ship_to_state',
            field=models.CharField(default='发货州', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='ship_to_zipcode',
            field=models.CharField(default='发货zipcode', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='size',
            field=models.CharField(default='尺寸', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='sleeve',
            field=models.CharField(default='袖子', max_length=50, null=True),
        ),
    ]
