# Generated by Django 3.2.2 on 2022-06-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20220615_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='color',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='quotation_id',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='receiver_tel',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='rep_id',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='req_image',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='ship_to_city',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='ship_to_state',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='ship_to_zipcode',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='size',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='sleeve',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='update_date',
        ),
    ]
