# Generated by Django 4.0.4 on 2022-06-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20220615_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='email',
            field=models.CharField(default='email@email.com', max_length=300),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='firstName',
            field=models.CharField(default='First Name', max_length=300),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='lastName',
            field=models.CharField(default='Last Name', max_length=300),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='tel',
            field=models.CharField(default='Telphone', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='ship_to_address',
            field=models.CharField(default='address', max_length=100),
        ),
    ]
