# Generated by Django 4.0.4 on 2022-06-15 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0007_alter_quoinprog_quotation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0009_ordermaster_email_ordermaster_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermaster',
            options={'ordering': ['order_id'], 'verbose_name': 'Order', 'verbose_name_plural': 'Order'},
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='category_name',
            field=models.ForeignKey(default=2, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='customize.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='color',
            field=models.CharField(default='颜色', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='客户'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='description',
            field=models.CharField(blank=True, default='需求描述', max_length=230, null=True, verbose_name='需求描述'),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='gender',
            field=models.CharField(default='性别', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='part_number',
            field=models.CharField(default='物料编码', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='quantity',
            field=models.IntegerField(default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='quotation_id',
            field=models.IntegerField(default=1652516905, verbose_name='询价号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='rep_id',
            field=models.BooleanField(default=False, verbose_name='accounts.Ouser'),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='req_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='定制样式图片'),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='ship_to_address2',
            field=models.CharField(blank=True, default='address2', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='ship_to_country',
            field=models.CharField(default='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='ship_to_state',
            field=models.CharField(default='State', max_length=50),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='ship_to_zipcode',
            field=models.CharField(default='Zipcode', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='size',
            field=models.CharField(default='尺寸', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='sleeve',
            field=models.CharField(default='袖子', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='order_id',
            field=models.IntegerField(verbose_name='Order id'),
        ),
    ]
