# Generated by Django 4.0.4 on 2022-06-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_ordermaster_options_ordermaster_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='total_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='quotation_id',
            field=models.IntegerField(default='quotationid'),
        ),
    ]
